# Generated by Django 5.2.6 on 2026-05-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.adminprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManagementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('stock', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('product_image', models.ImageField(null=True, upload_to='media/product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.adminprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('payment_method', models.CharField(choices=[('COD', 'COD'), ('Online', 'Online')], max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50, null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Shipped', 'Shipped'), ('Deliverd', 'Deliverd')], default='Pending', max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.customerprofilemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.productmanagementmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.customerprofilemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerceApp.productmanagementmodel')),
            ],
        ),
    ]
